### ISSUE TITLE
Error while compiling the singularity container

### ISSUE THREAD

**Issue by walee-1** [i2bc/SCAN_IDR#1]
Hi,
I am having trouble following the said instructions, where I get the following error: 

/.post.script: line 123: cd: /opt/conda/lib/python3.7/site-packages/colabfold/: No such file or directory
/.post.script: line 150: cd: /opt/conda/lib/python3.7/site-packages/colabfold/: No such file or directory
FATAL:   While performing build: while running engine: exit status 1

I am trying to compile this for cluster use and am not super familiar with colabfold. Which brings me to my 2 questions I have:
If I were to change your singularity with a locally installed non container colabfold version, where do I make the appropriate changes in your code.

Or if the singularity is really required, please can you help me solve the aforementioned issue.

Lastly, I am trying to install this on Debian12 but I don't believe that should be the issue as the container should be os independent

**Comment by jessica-andreani** [comment]
Hello, thanks for your interest.

Are you running the singularity build command with root privileges? As said in the instructions "To create the colabfold singularity image, root privilege is needed and the command below may be more easily performed on a local linux machine even without GPUs. Once built, the file colabfold_container_v13.sif can be copied to the machine running the scan_idr pipeline such as a server or a cluster preferentially with GPUs."

Otherwise, if you would like to run ColabFold independently of the container version, you would need to change the [run_colab_template.sh](https://github.com/i2bc/SCAN_IDR/blob/master/scripts/run_colab_template.sh) script (where we are running colabfold_batch through the singularity container).

Please let us know if this solves your problem, otherwise we'll investigate possible workarounds.

**Comment by walee-1** [comment]
Yes I am running the installation of the singularity container as sudo on my local machine but I can just use the second hint you provided to go around this issue as I have a working colabfold version available. Thank you

**Comment by jessica-andreani** [comment]
Hello, did you solve this? Thank you

**Comment by walee-1** [comment]
Hi, I was installing this on our HPC environment for a user, I believe I got around it with the workaround that the user will have a copy of the pipeline, which they can edit to their needs (as we have currently multiple colabfold versions and 2 databases) and run it. However, they have not tested it as of now. Please feel free to close this as solved for now and in case we run across issues I will get back to you.

Also I did this in a python virtual environment with all the other non-python conda dependencies being loaded through a module system.

**Comment by jessica-andreani** [comment]
Thanks for your feedback! As you suggested, closing the issue for now, please let us know if you have other issues.
